[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "shared-schemas"
version = "0.1.0"
dependencies = [
    "pydantic",
    "fastapi" 
]

[tool.hatch.build.targets.wheel]
packages = ["src/shared_schemas"]